version: 2.1
jobs:
  Setup-Project:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Running the Node Container
          command: |
            npm ci
            node -v
  Lint:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Running linter on the project
          command: |
            npm ci
            npm run lint
  Type-Check:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Running type checking on the project
          command: |
            npm ci
            npm run type-check
  Build:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Building the project
          command: |
            npm ci
            npm run build
  Test:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Running the unit tests
          command: |
            npm ci
            npm run test

workflows:
  Build-Workflow:
    jobs:
      - Setup-Project
      - Lint:
          requires:
            - Setup-Project
      - Type-Check:
          requires:
            - Setup-Project
      - Build:
          requires:
            - Type-Check
      - Test:
          requires:
            - Type-Check
